Django_team_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('posting/', include('posting.urls')),
    path('main/', views.main_view, name='main_view'),
    path('', views.main_view, name='main_view'),
    path('comment/',include('comment.urls')),
]

user/urls.py
from django.urls import path
from user import views

app_name = 'user'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('user_info/', views.search_info, name='search_info'),
    path('mypage/', views.mypage, name='mypage'),
    path('myposting/', views.myposting, name='myposting'),
    path('edit/', views.edit, name='edit'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>임당귀</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
            crossorigin="anonymous"></script>

    <!--jQuery-->
    <!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->

    <style>
        a {
            text-decoration-line: none;
        }

        .title-center {
            text-align: center;
            margin-top: 50px;
        }

        .wrap {
            width: 400px;
            margin: 0 auto;
        }

        .form-area {
            margin-top: 25px;
        }

        .timeline-container {
            margin-top: 25px
        }

        .nav-link {
            font-size: 14px;
        }

        .navbar-brand {
            font-size: 14px;
        }

        #container_img {
            margin-left: 90px;
        }

        /*네비*/
        .nav_main {
            background-color: black;
            display: flex;
            padding: 10px 30% 10px 30%;
            width: 100%;
            /*div 가운데 정렬*/
            text-align: center;
            justify-content: space-around;
        }

        #nav_text {
            display: inline-block;
            text-decoration-line: none;
            margin-left: 10px;
            margin-right: 10px;
            color: white;
        }

        .terms_choice {
            font-size: 13px;
            color: lightgray;
        }

        .btn-secondary {
            margin-left: 2px;
            margin-bottom: 2px;
        }

        .search_bar {
            margin-right: 100px;
        }

    </style>
</head>

<body>

<div class="nav_cont">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="/main"><h1>임금님귀는 당나귀 귀</h1></a>
            <a href="/main"><img id="container_img" src="https://i.postimg.cc/T16pDXNT/1.png" alt="로고"></a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                    </li>
                </ul>
            </div>
            <form class="form-area search_bar" method="get" action='{% url 'user:search_info' %}'>
                <div class=" form-group mt-2 mb-2">
                    <input type="text" class="form-control" placeholder="유저 검색" id="search_user" name="search_user">
                </div>
            </form>
            {% if not user.is_authenticated %}
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <button type="button"
                                onclick="location.href = '{% url 'user:signup' %}?next={{ request.path }}'"
                                class="btn btn-secondary">회원가입
                        </button>
                    </li>
                    <li class="nav-item active">
                        <button type="button"
                                onclick="location.href = '{% url 'user:login' %}?next={{ request.path }}'"
                                class="btn btn-secondary">로그인
                        </button>
                    </li>
                    <button type="button" onclick="location.href = '{% url 'user:login' %}?next=/posting/create'"
                            class="btn btn-secondary">글쓰기
                    </button>
                </ul>
            {% else %}
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <h4>{{ user.username }} 님 반갑습니다.</h4>
                        <button type="button"
                                onclick="location.href = '{% url 'user:logout' %}?next={{ request.path }}'"
                                class="btn btn-secondary">로그아웃
                        </button>
                        <button type="button" onclick="location.href = '/user/mypage'"
                                class="btn btn-secondary">
                            마이페이지
                        </button>
                        <button type="button" onclick="location.href = '/posting/create'"
                                class="btn btn-secondary">
                            글쓰기
                        </button>
                    </li>
                </ul>
            {% endif %}
            </form>
        </div>
    </nav>
        <!-- 네비 -->
        <div class="nav_main">
            <div class="category-box"><b><a id="nav_text{% if not category %} {% endif %}"
                                            href="{% url 'posting_list' %}">전
                체 목 록</a></b></div>

            <div class="category-box codereview">
                <b><a id="nav_text{% if category == 'codereview' %} {% endif %}"
                      href="{% url 'posting_list' 'codereview' %}">코 드 리 뷰</a></b>
            </div>

            <div class="category-box course">
                <b><a id="nav_text{% if category == 'course' %} {% endif %}"
                      href="{% url 'posting_list' 'course' %}">취 업 진 로</a></b>
            </div>

            <div class="category-box coding_study">
                <b><a id="nav_text{% if category == 'coding_study' %} {% endif %}"
                      href="{% url 'posting_list' 'coding_study' %}">개 발 공 부</a></b>
            </div>

            <div class="category-box free_board">
                <b><a id="nav_text{% if category == 'free_board' %} {% endif %}"
                      href="{% url 'posting_list' 'free_board' %}">잡 담</a></b>
            </div>

            <div class="category-box study">
                <b><a id="nav_text{% if category == 'study' %} {% endif %}"
                      href="{% url 'posting_list' 'study' %}">스 터 디</a></b>
            </div>
        </div>

    <div class="container">
        {% block content %}{% endblock %}
    </div>
</div>
</div>
</body>

</html>

templates/main.html
<!-- templates/tweet/home.html -->
{% extends 'base.html' %}

{% block content %}
    <style>
        .banner img {
            margin-top: 20px;
            width: 100%;
        }

        .main_posts {
            /*(부모)자식 위치잡기위해*/
            position: relative;
            display: flex;
            justify-content: space-between;
        }


        /*메인 리스트박스*/
        .main_post {
            margin: 20px;
            padding: 5px;
            width: 500px;
            height: 300px;
            border-top: 1px solid rgb(185, 185, 185);
            border-bottom: 1px solid rgb(185, 185, 185);
            /*텍스트가 표시되는 영역을 벗어났을 때 남은 글자 안보이게 함*/
            overflow: hidden;
        {#margin-right: auto;#}{#margin-left: auto;#}

        }

        .main_post_div {
            margin-bottom: 10px;
        }

        .main_post_list li {
            list-style-type: none;
            margin-bottom: 6px;
            /*div 양쪽정렬*/
            display: flex;
            justify-content: space-between;
        }

        .main_post_list li div {
            display: inline-block;
        }

        .main_headline {
            /*하이퍼링크 밑줄 없애기*/
            text-decoration-line: none;
            color: black;
            font-size: 20px;
            /*글씨 굵게*/
            font-weight: bold;
        }

        #posting_list_id {
            text-decoration-line: none;
            color: black;
            /*길이 제한*/
            display: block;
            width: 350px;
            /*텍스트가 표시되는 영역을 벗어났을 때 남은 글자 안보이게 함*/
            overflow: hidden;
            /*생략기호 사용*/
            text-overflow: ellipsis;
            /*텍스트가 길어지면 줄 바꿈을 하지 않도록 함*/
            white-space: nowrap;

        }

        .


    </style>
    <div class="banner">
        <img src="https://i.postimg.cc/kgSxrYC3/image.png"/>
    </div>
    <form method="get" action="/main">
        <div class="main_posts row row-cols-1 row-cols-md-2 g-4">

            <!--카테고리별로 나눠져서 보기-->
            <!--코드리뷰-->
            <div class="main_post">
                <div class="main_post_div">
                    <div class="main_headline_div">
                        <a class="main_headline" href="/">코드리뷰</a>
                        <hr style="border: solid 1px red; width: 15%; margin-top: 3px;">
                    </div>
                </div>
                <!--여기 리스트를 하나만 작성한 다음에 아래 착착붙게 반복문 사용-->
                <!-- <div>
                
                {% if postings %}
                <ul>
                    {% for posting in postings %}
                    <li>
                        <div class="posting_list_div">
                            
                            <a id="posting_list_id">{{ posting.title }}</a>
                        </div>
                        <div class="posting_id_div">
                            <span class="posting_id">{{ posting.username }}</span>
                        </div>
                    {% endfor %}
                </ul>
                {% else %}
                        <p>작성된 글이 없습니다.</p>
                {% endif %}
            </div> -->
                <div class="main_post_list" id="post_list_codereview">
                    {% if postings %}
                        <ul>
                            {% for posting in postings %}
                                {% if posting.category == 'codereview' %}
                                    <li>
                                    <div class="posting_list_div">

                                        <b><a id="posting_list_id"
                                              href="{% url 'posting_detail' posting.posting_id %}">{{ posting.title }}</a></b>
                                    </div>
                                    <div class="posting_id_div">
                                        <span class="posting_id">{{ posting.username }}</span>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p>작성된 글이 없습니다.</p>
                    {% endif %}
                </div>
            </div>


            <!--취업진로-->
            <div class="main_post">
                <div class="main_post_div">
                    <div class="main_headline_div">
                        <a class="main_headline" href="/">취업진로</a>
                        <hr style="border: solid 1px red; width: 15%; margin-top: 3px;">
                    </div>
                </div>
                <div class="main_post_list" id="post_list_course">
                    {% if postings %}
                        <ul>
                            {% for posting in postings %}
                                {% if posting.category == 'course' %}
                                    <li>
                                    <div class="posting_list_div">

                                        <b><a id="posting_list_id"
                                              href="{% url 'posting_detail' posting.posting_id %}">{{ posting.title }}</a></b>
                                    </div>
                                    <div class="posting_id_div">
                                        <span class="posting_id">{{ posting.username }}</span>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p>작성된 글이 없습니다.</p>
                    {% endif %}
                </div>
            </div>

            <!--개발공부-->
            <div class="main_post">
                <div class="main_post_div">
                    <div class="main_headline_div">
                        <a class="main_headline" href="/">개발공부</a>
                        <hr style="border: solid 1px red; width: 15%; margin-top: 3px;">
                    </div>
                </div>
                <div class="main_post_list" id="post_list_coding_study">
                    {% if postings %}
                        <ul>
                            {% for posting in postings %}
                                {% if posting.category == 'coding_study' %}
                                    <li>
                                    <div class="posting_list_div">

                                        <b><a id="posting_list_id"
                                              href="{% url 'posting_detail' posting.posting_id %}">{{ posting.title }}</a></b>
                                    </div>
                                    <div class="posting_id_div">
                                        <span class="posting_id">{{ posting.username }}</span>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p>작성된 글이 없습니다.</p>
                    {% endif %}
                </div>
            </div>

            <!--스터디-->
            <div class="main_post">
                <div class="main_post_div">
                    <div class="main_headline_div">
                        <a class="main_headline" href="/">스터디</a>
                        <hr style="border: solid 1px red; width: 15%; margin-top: 3px;">
                    </div>
                </div>
                <div class="main_post_list" id="post_list_study">
                    {% if postings %}
                        <ul>
                            {% for posting in postings %}
                                {% if posting.category == 'study' %}
                                    <li>
                                    <div class="posting_list_div">

                                        <b><a id="posting_list_id"
                                              href="{% url 'posting_detail' posting.posting_id %}">{{ posting.title }}</a></b>
                                    </div>
                                    <div class="posting_id_div">
                                        <span class="posting_id">{{ posting.username }}</span>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p>작성된 글이 없습니다.</p>
                    {% endif %}
                </div>
            </div>

            <!--잡담-->
            <div class="main_post">
                <div class="main_post_div">
                    <div class="main_headline_div">
                        <a class="main_headline" href="/">잡담</a>
                        <hr style="border: solid 1px red; width: 15%; margin-top: 3px;">
                    </div>
                </div>
                <div class="main_post_list" id="post_list_free_board">
                    {% if postings %}
                        <ul>
                            {% for posting in postings %}
                                {% if posting.category == 'free_board' %}
                                    <li>
                                    <div class="posting_list_div">
                                        <b><a id="posting_list_id"
                                              href="{% url 'posting_detail' posting.posting_id %}">{{ posting.title }}</a></b>
                                    </div>
                                    <div class="posting_id_div">
                                        <span class="posting_id">{{ posting.username }}</span>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p>작성된 글이 없습니다.</p>
                    {% endif %}
                </div>
            </div>
        </div> <!--main_post-->
        </div><!--main_posts-->
    </form>
{% endblock %}